apiVersion: v1
kind: Secret
metadata:
  name: pingera-sb-secrets
type: Opaque
stringData:
  APP_URL: 
  APP_DEBUG: 
  APP_KEY: ""
  LOG_LEVEL: "debug"
  DB_CONNECTION: "pgsql"
  DB_HOST: ''
  DB_PORT: '5432'
  DB_DATABASE: ''
  DB_USERNAME: ''
  DB_PASSWORD: ''
  REDIS_HOST: '' 
  REDIS_PASSWORD: ''
  TELEGRAM_TOKEN: ''
  TELEGRAM_SECRET_KEY: ''
  TELEGRAM_GROUP_ID: ''
  APP_LOCALE: ""  


